# Generated by Django 3.0.5 on 2021-01-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(unique=True),
        ),
    ]
